name: SCHEDULE

on: 
 push:    
#  schedule:
#     - cron : '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up nodejs and install dependencies
    - uses: actions/setup-node@v1
      with:
      node-version: '12'
    - run: npm install -g yarn
    - run: yarn
    
